GET http://localhost:3000/posts 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTY4ODEzNTI5MSwiZXhwIjoxNjg4MTM1MzA2fQ.FLdi0DnsZ9WKp3LQjIX3R_hC5SVHmuR-pRfy-a7nuPg

###

POST http://localhost:4000/login
Content-Type: application/json

{
     "username": "Kyle"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
     "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTY4ODEzNTI2NX0.jvbUyaHGcgb0WLkAYRPyzsBZWibpXgIuVaqDtIPGmWs"
}