GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODgwNDg0MjB9.CnURp6NOoGbZS3jsv80NitFlRGaWWtgH1ICIe1-cQBk

###

POST http://localhost:3000/login
Content-Type: :"application/json"

{
     "username": "Kyle"
}